# This workflow push and deploy the app onto heorku

name: Deploy to heroku

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to Heroku Container registry
      env: 
        HEROKU_API_KEY: bdb5e0e7-b4c5-4c33-984e-6d604cfe9352
      run: heroku container:login 
    - name: Build and push
      env:
        HEROKU_API_KEY: bdb5e0e7-b4c5-4c33-984e-6d604cfe9352
      run: heroku container:push -a crazy-thurs web 
    - name: Release
      env:
        HEROKU_API_KEY: bdb5e0e7-b4c5-4c33-984e-6d604cfe9352
      run: heroku container:release -a crazy-thurs web 
